### ISSUE TITLE
The referenced twilio=6.1.0-alpha1 library can't be found

### ISSUE THREAD

**Issue by pshafton** [TwilioDevEd/sdk-starter-python#19]
When I run pip install -r requirements.txt I get the following output...

Could not find a version that satisfies the requirement twilio==6.1.0-alpha1 (from -r requirements.txt (line 3)) (from versions: 6.2.0, 3.6.5, 3.4.3, 5.5.0, 4.6.0, 4.3.0, 3.7.2, 2.0.1, 5.0.dev3, 5.0.dev2, 4.1.0, 6.0.0rc10, 3.3.10, 3.5.4, 3.3.9, 6.2.0, 5.7.0, 3.6.7, 6.1.1, 3.6.8, 6.0.0rc11, 5.0.dev1, 4.9.dev0, 2.0.10, 2.0.6, 3.5.2, 3.0.1, 3.6.6, 3.6.4, 4.2.0, 3.6.0, 3.2.1, 3.6.2, 6.0rc9, 5.6.1, 6.1.0, 3.4.4, 4.9.0, 4.2.0, 5.2.0, 6.0rc8, 3.2.3, 6.1.1a1, 3.5.1, 3.6.14, 6.0.0rc11, 3.0.0, 5.0.dev0, 3.0.2, 6.1.1, 3.6.3, 3.7.2, 5.6.1, 3.6.13, 6.1.2, 3.7.0, 3.5.3, 5.4.0, 3.4.0, 3.7.3, 4.8.0, 3.7.1, 6.0rc7, 3.1.0, 5.0.0, 6.0rc5, 4.7.dev0, 3.6.6, 3.6.15, 3.6.10, 5.1.0, 6.0.0rc13, 3.7.1, 5.3.0, 3.2.0, 3.2.2, 6.0.0a1, 6.1.2-alpha-1, 3.6.11, 3.4.2, 6.1.0a1, 6.0rc6, 3.3.0, 3.5.4-rc1, 4.9.2, 6.1.2, 6.1.1a1, 3.3.3, 3.6.1, 3.7.3, 6.0.0rc10, 3.6.12, 3.6.14, 3.6.12, 6.1.dev0, 3.4.1, 6.0.dev0, 3.6.11, 3.4.5, 4.9.1, 2.0.9, 3.6.4, 3.3.2, 6.0rc4, 6.0.0rc12, 4.7.0, 3.8.0, 4.5.0, 3.7.0, 4.10.0, 5.6.0, 6.2.dev0, 4.8.dev0, 3.6.9, 3.5.0, 6.0.0rc12, 4.4.0, 3.6.10, 6.1.0, 6.0.0rc2, 3.3.11, 3.8.0, 4.1.0, 6.1.2-alpha-1, 3.3.7, 3.6.13, 6.0rc3, 4.0.0, 6.3.dev0, 3.3.6, 3.3.1, 6.0.0, 3.6.9, 3.3.5)
Cleaning up...
No distributions matching the version for twilio==6.1.0-alpha1 (from -r requirements.txt (line 3))

**Comment by jefflinwood** [comment]
Will update to 6.2.0-alpha1

**Comment by jefflinwood** [comment]
Fixed in https://github.com/TwilioDevEd/sdk-starter-python/pull/20

Thanks!
