### ISSUE TITLE
issues with later chat sdks

### ISSUE THREAD

**Issue by SeekTom** [TwilioDevEd/sdk-starter-python#35]
Using this with chat 1.2 works fine, 2.2/3.0 all have issues in this section:
 var channel = 'CHXXXXXXXXXXXXXXXXXX';
  var promise = chatClient.getChannelBySid(channel);
       
        promise.then(function(channel) {
                    generalChannel = channel;
                    setupChannel();
                }).catch(function(){
                    // If it doesn't exist, let's create it
            
                    chatClient.createChannel({
                        uniqueName: 'general',
                        friendlyName: 'General Chat Channel'
            }).then(function(channel) {
                console.log('Created general channel:');
                console.log(channel);
                generalChannel = channel;
                setupChannel();
            });
        });
    }

Seems to ignore or be unable to handle the returned promise? The best way to test is to use the same code and just switch the js libraries to 2.2 and 3.0.

**Comment by po5i** [comment]
Recently the code base was updated to use chat v3. I just tested and everything works good!

Thanks for the feedback
