### ISSUE TITLE
The chat front end is BROKEN!!

### ISSUE THREAD

**Issue by sicongliu-DD** [TwilioDevEd/sdk-starter-python#41]
Uncaught TypeError: Cannot read property 'sendMessage' of undefined

` // Send a new message to the general channel
  var $input = $('#chat-input');
  $input.on('keydown', function(e) {
    if (e.keyCode == 13) {
      generalChannel.sendMessage($input.val())
      $input.val('');
    }
  });`

**Comment by jefflinwood** [comment]
Hi,

That's frustrating! Do you have a Chat Service SID in the .env file? It's commented out by default, so that might be one cause of this issue.

Hope we can get this going for you!

**Comment by sicongliu-DD** [comment]
ah, that solved the issue. Thanks!!
